package com.loloof64.reactnativestockfish

import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.WritableMap
import com.facebook.react.bridge.Arguments
import com.facebook.react.modules.core.DeviceEventManagerModule
import kotlinx.coroutines.*

/**
 * TurboModule implementation for New Architecture.
 * 
 * This class extends the codegen-generated NativeReactNativeStockfishSpec base class.
 * The base class is generated by React Native's codegen during the app build process
 * at: android/app/build/generated/source/codegen/java/com/loloof64/reactnativestockfish/NativeReactNativeStockfishSpec.java
 * 
 * React Native's build system automatically:
 * 1. Runs codegen to generate the base class
 * 2. Compiles this implementation (which extends the base class)
 * 3. Links everything together
 * 
 * Note: This file will only compile when built as part of an app with New Architecture enabled.
 */
class ReactNativeStockfishModuleImpl(
  reactContext: ReactApplicationContext
) : com.loloof64.reactnativestockfish.NativeReactNativeStockfishSpec(reactContext) {

  companion object {
    const val NAME = ReactNativeStockfishModule.NAME
    
    @Volatile
    private var globalIsRunning = false
    private var globalOutputReaderCoroutineScope: CoroutineScope? = null
    private var globalErrorReaderCoroutineScope: CoroutineScope? = null
    private var globalStockfishThread: Thread? = null
    private var globalReactContext: ReactApplicationContext? = null
    
    private fun stopGlobalInstance() {
      globalIsRunning = false
      globalOutputReaderCoroutineScope?.cancel()
      globalErrorReaderCoroutineScope?.cancel()
      globalStockfishThread?.interrupt()
      globalOutputReaderCoroutineScope = null
      globalErrorReaderCoroutineScope = null
      globalStockfishThread = null
    }
  }

  private val mainCoroutineScope = CoroutineScope(Dispatchers.Default)
  private var outputReaderCoroutineScope = CoroutineScope(Dispatchers.Default)
  private var errorReaderCoroutineScope = CoroutineScope(Dispatchers.Default)
  private var stockfishThread: Thread? = null
  private var isRunning = false

  external fun main()
  external fun stdoutRead(): String?
  external fun stderrRead(): String?
  external fun stdinWrite(command: String)

  init {
    System.loadLibrary("react-native-stockfish")
    if (globalIsRunning) {
      android.util.Log.w("ReactNativeStockfish", "New module instance created while old one is running - stopping old instance")
      stopGlobalInstance()
      Thread.sleep(300)
    }
    globalReactContext = reactContext
  }

  override fun getName(): String {
    return NAME
  }

  override fun stockfishLoop() {
    if (globalIsRunning) {
      android.util.Log.w("ReactNativeStockfish", "Stopping existing global instance before starting new one")
      stopGlobalInstance()
      Thread.sleep(300)
    }
    
    if (isRunning) {
      stopStockfish()
      Thread.sleep(200)
    }
    
    globalIsRunning = true
    isRunning = true
    globalReactContext = reactApplicationContext
    val delayTimeMs = 1L
    
    outputReaderCoroutineScope = CoroutineScope(Dispatchers.Default)
    errorReaderCoroutineScope = CoroutineScope(Dispatchers.Default)
    globalOutputReaderCoroutineScope = outputReaderCoroutineScope
    globalErrorReaderCoroutineScope = errorReaderCoroutineScope
    
    stockfishThread = Thread {
      Thread.sleep(delayTimeMs)
      main()
      isRunning = false
      globalIsRunning = false
    }
    globalStockfishThread = stockfishThread
    stockfishThread?.start()
    
    outputReaderCoroutineScope.launch {
      while (isRunning && globalIsRunning) {
        try {
          val output = stdoutRead()
          if (output != null && output.isNotEmpty()) {
            val eventMap: WritableMap = Arguments.createMap()
            eventMap.putString("output", output)
            reactApplicationContext
              .getNativeModule(DeviceEventManagerModule.RCTDeviceEventEmitter::class.java)
              ?.emit("stockfish-output", eventMap)
          }
          delay(1)
        } catch (e: Exception) {
          if (isRunning) {
            android.util.Log.e("ReactNativeStockfish", "Error reading stdout", e)
          }
          break
        }
      }
    }
    
    errorReaderCoroutineScope.launch {
      while (isRunning && globalIsRunning) {
        try {
          val error = stderrRead()
          if (error != null && error.isNotEmpty()) {
            val eventMap: WritableMap = Arguments.createMap()
            eventMap.putString("error", error)
            reactApplicationContext
              .getNativeModule(DeviceEventManagerModule.RCTDeviceEventEmitter::class.java)
              ?.emit("stockfish-error", eventMap)
          }
          delay(1)
        } catch (e: Exception) {
          if (isRunning) {
            android.util.Log.e("ReactNativeStockfish", "Error reading stderr", e)
          }
          break
        }
      }
    }
  }

  override fun sendCommandToStockfish(command: String) {
    if (isRunning && globalIsRunning) {
      stdinWrite(command)
    } else {
      android.util.Log.w("ReactNativeStockfish", "Cannot send command: Stockfish is not running")
    }
  }

  override fun stopStockfish() {
    if (isRunning || globalIsRunning) {
      isRunning = false
      globalIsRunning = false
      outputReaderCoroutineScope.cancel()
      errorReaderCoroutineScope.cancel()
      stockfishThread?.interrupt()
      stopGlobalInstance()
    }
  }

  override fun invalidate() {
    super.invalidate()
    stopStockfish()
  }
}

